analytics: {}
color:
  brandColors:
    - '#B0B8B8'
    - '#900818'
    - '#905050'
    - '#B81030'
    - '#000000'
  brandStrength: 0.644737
  lightness: 0.508224
  rhythmicContrast: 0.5
  saturation: 0.60773
cta: {}
layout_spectrum: 0.919408
name: Bayly Grandchildren
opengraph: {}
purpose: []
typography_spectrum: 0.476151
